services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: it_helpdesk
      POSTGRES_PASSWORD: "CRC@123!!!"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file: ./helpdesk/.env
    environment:
      DATABASE_URL: "postgresql://it_helpdesk:CRC%40123%21%21%21@db:5432/helpdesk_db"
      ALLOWED_HOSTS: "itservicedesk.creditreferencenigeria.net,localhost"
      DEBUG: "False"
    depends_on:
      - db
    volumes:
      - media_data:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn helpdesk.wsgi --bind 0.0.0.0:8000 --workers 2 --threads 4 --timeout 120"

volumes:
  postgres_data:
  media_data:
